import '../app/explanation-audio.css';
import React from 'react';
import {createRoot} from 'react-dom/client';
import Ruimteklaar from '../app/ruimteklaar';
import {KnowledgeProvider} from '../app/knowledge/context';
import '../app/globals.css';
import '../app/construction-selection.css';
import '../app/knowledge/knowledge.css';
import '../app/entry-choice.css';
createRoot(document.getElementById('root')!).render(<KnowledgeProvider><Ruimteklaar local/></KnowledgeProvider>);
