'use client';
import {useId,useState,type ReactNode} from 'react';
import Geometry from '../geometry';
import {SCENES,footExample,areaRectangle} from './figure-data';

const orange='#ffba80',mint='#74e4d0',purple='#c7b0ff',ink='#d5e5ef';
type P=[number,number];
function Line({a,b,color=ink,dashed=false}:{a:P;b:P;color?:string;dashed?:boolean}){return <line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke={color} strokeWidth="2.5" strokeDasharray={dashed?'6 5':undefined}/>}
function Label({p,children,color=ink}:{p:P;children:ReactNode;color?:string}){return <text x={p[0]} y={p[1]} fill={color} textAnchor="middle">{children}</text>}
function Point({p,name,below=false}:{p:P;name:string;below?:boolean}){return <g><circle cx={p[0]} cy={p[1]} r="4" fill={orange}/><Label p={[p[0],p[1]+(below?24:-13)]}>{name}</Label></g>}
function Polygon({points,color=mint}:{points:P[];color?:string}){return <polygon points={points.map(p=>p.join(',')).join(' ')} fill={color+'18'} stroke={color} strokeWidth="2.5"/>}
function Right({p,u=[1,0],v=[0,-1]}:{p:P;u?:P;v?:P}){const s=12;return <polyline points={[[p[0]+s*u[0],p[1]+s*u[1]],[p[0]+s*(u[0]+v[0]),p[1]+s*(u[1]+v[1])],[p[0]+s*v[0],p[1]+s*v[1]]].map(p=>p.join(',')).join(' ')} stroke={orange} strokeWidth="2" fill="none"/>}
function Canvas({caption,children}:{caption:string;children:ReactNode}){const id='knowledge-figure-'+useId().replaceAll(':','');return <figure className="knowledge-illustration"><svg viewBox="0 0 480 300" role="img" aria-labelledby={id}><title id={id}>{caption}</title>{children}</svg><figcaption>{caption}</figcaption></figure>}
const round=(x:number)=>x.toLocaleString('nl-NL',{maximumFractionDigits:2});

function Foot({outside=false,steps=false}:{outside?:boolean;steps?:boolean}){
 const [x,setX]=useState(outside||steps?3:1),[stage,setStage]=useState(3),[walking,setWalking]=useState(false);
 const e=footExample(x),px=120+x*70,base=220,top=150;
 const captions=['Gegeven: P en de lijn door A en B. De lijn loopt aan beide kanten door.','Trek door P de loodlijn op AB. In deze vlakke figuur is AB horizontaal, dus de loodlijn verticaal.','Het snijpunt van de loodlijn met AB is F, de loodvoet. F kan buiten het lijnstuk AB liggen.','PF is de afstand tot de volledige lijn. Bij een lijnstuk controleer je bovendien of F tussen A en B ligt.'];
 return <div className="knowledge-demo"><Canvas caption={`A = (0,0), B = (2,0), P = (${round(x)},1). ${captions[stage]}`}>
  <Line a={[30,base]} b={[450,base]} dashed/><Line a={[120,base]} b={[260,base]} color={mint}/><Label p={[435,base-12]}>l</Label>
  <Point p={[120,base]} name="A" below/><Point p={[260,base]} name="B" below/><Point p={[px,top]} name="P"/>
  {stage>=1&&<Line a={[px,70]} b={[px,265]} color={purple} dashed/>}
  {stage>=2&&<><circle cx={px} cy={base} r="4" fill={orange}/><Label p={[px,284]} color={orange}>F</Label><Right p={[px,base]}/></>}
  {stage>=3&&<><Line a={[px,top]} b={[px,base]} color={orange}/><Label p={[px+26,190]} color={orange}>1</Label>{!e.inside&&<Line a={[px,top]} b={[x<0?120:260,base]} color={mint} dashed/>}</>}
 </Canvas>
 <div className="knowledge-demo-controls"><label>Verplaats P horizontaal <input aria-label="Horizontale plaats van P" type="range" min="-1" max="4" step="0.1" value={x} onChange={ev=>setX(Number(ev.target.value))}/></label>
 {steps&&!walking&&<button type="button" className="knowledge-start-steps" onClick={()=>{setStage(0);setWalking(true)}}>Bouw de loodvoet stap voor stap</button>}
 {steps&&walking&&<div className="knowledge-step-buttons"><button type="button" disabled={stage===0} onClick={()=>setStage(s=>s-1)}>Vorige stap</button><span>Stap {stage+1} van 4</span><button type="button" disabled={stage===3} onClick={()=>setStage(s=>s+1)}>Volgende stap</button></div>}
 {stage>=3&&<p role="status">Afstand tot de lijn: 1. Afstand tot lijnstuk AB: {round(e.segmentDistance)}. {e.inside?'F ligt op AB.':'F ligt buiten AB; voor het lijnstuk is het dichtstbijzijnde eindpunt bepalend.'}</p>}
 </div></div>;
}
function Views(){const [view,setView]=useState<'spatial'|'front'|'top'|'right'>('spatial');return <div className="knowledge-demo"><div className="knowledge-view-buttons">{([['spatial','Ruimtelijk'],['front','Voor'],['top','Boven'],['right','Zij']] as const).map(([v,name])=><button type="button" key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{name}</button>)}</div><Geometry key={view} compact guidance={false} view={view} fixed={view!=='spatial'} dimensions={[6,4,3]} caption="Balk met breedte 6, diepte 4 en hoogte 3. Voor toont 6 × 3, boven 6 × 4 en zij 4 × 3. Punten achter elkaar kunnen samenvallen in een aanzicht."/></div>}
function FunctionDemo(){const [x,setX]=useState(5),y=areaRectangle(x),f=(t:number):P=>[50+38*t,250-7*areaRectangle(t)];return <div className="knowledge-demo"><Canvas caption="A(x) = x(10 − x): oppervlakte van een rechthoek met omtrek 20. Voor echte rechthoeken geldt 0 < x < 10. Het maximum is 25 bij x = 5."><Line a={[50,250]} b={[445,250]}/><Line a={[50,250]} b={[50,42]}/><Label p={[453,269]}>x</Label><Label p={[35,30]}>A</Label>{[0,5,10].map(t=><Label key={t} p={[f(t)[0],277]}>{t}</Label>)}{[10,20,25].map(t=><g key={t}><Line a={[50,250-7*t]} b={[430,250-7*t]} color="#415b6c" dashed/><Label p={[27,255-7*t]}>{t}</Label></g>)}<polyline fill="none" stroke={mint} strokeWidth="3" points={Array.from({length:101},(_,i)=>f(i/10).join(',')).join(' ')}/><Line a={[f(x)[0],250]} b={f(x)} color={orange} dashed/><Point p={f(x)} name={`(${round(x)}; ${round(y)})`}/>{[0,10].map(t=><circle key={t} cx={f(t)[0]} cy={250} r="4" fill="#0c1c2a" stroke={mint} strokeWidth="2"/>)}</Canvas><div className="knowledge-demo-controls"><label>Kies de breedte x <input type="range" min="0.2" max="9.8" step="0.1" value={x} onChange={e=>setX(Number(e.target.value))}/></label><p role="status">Breedte {round(x)} cm · lengte {round(10-x)} cm · oppervlakte {round(y)} cm²</p></div></div>}
function Dynamic(){const [bx,setBx]=useState(360),A:P=[90,225],B:P=[bx,75],M:P=[(90+bx)/2,150],length=Math.hypot(bx-90,-150),u:P=[(bx-90)/length,-150/length],v:P=[-u[1],u[0]];return <div className="knowledge-demo"><Canvas caption="A en B zijn uitgangspunten. M is hun geconstrueerde midden; de paarse lijn is de loodlijn op AB door M. Bij verschuiven van B blijven AM = MB en de loodrechte stand behouden."><Line a={A} b={B} color={mint}/><Line a={[M[0]-90*v[0],M[1]-90*v[1]]} b={[M[0]+90*v[0],M[1]+90*v[1]]} color={purple}/><Right p={M} u={u} v={v}/><Point p={A} name="A" below/><Point p={B} name="B"/><Point p={M} name="M" below/></Canvas><div className="knowledge-demo-controls"><label>Verplaats uitgangspunt B <input type="range" min="180" max="410" step="1" value={bx} onChange={e=>setBx(Number(e.target.value))}/></label><p>M blijft precies halverwege A en B.</p></div></div>}

export default function KnowledgeFigure({kind}:{kind:string}){
 const scene=SCENES[kind];if(scene)return <div className="knowledge-demo"><Geometry {...scene} compact guidance={false} fitToContent ariaLabel={scene.caption}/></div>;
 if(kind==='foot'||kind==='foot-outside'||kind==='foot-interactive')return <Foot outside={kind==='foot-outside'} steps={kind==='foot-interactive'}/>;
 if(kind==='views'||kind==='projection')return <Views/>;
 if(kind==='function')return <FunctionDemo/>;
 if(kind==='dynamic')return <Dynamic/>;
 if(['triangle','altitude','isosceles','equilateral','cosine'].includes(kind)){
  const iso=kind==='isosceles',equil=kind==='equilateral',cos=kind==='cosine';
  const A:P=equil?[120,240]:iso?[100,240]:[80,240],B:P=[360,240];
  const C:P=cos?[180,240-100*Math.sqrt(3)]:equil?[240,240-120*Math.sqrt(3)]:iso?[230,240-520/3]:[360,30];
  const H:P=kind==='altitude'?[259.2,105.6]:[C[0],240];
  const caption=cos?'Cosinusregel: bij A is de ingesloten hoek 60°, AB = 7 en AC = 5. De overstaande zijde BC is √39.':equil?'Gelijkzijdige driehoek met zijde 4. De hoogtelijn halveert de basis: twee stukken van 2. De hoogte is 2√3.':iso?'Gelijkbenige driehoek met zijden 5, 5 en 6. De top ligt boven het midden; de halve basis is 3 en de hoogte 4.':kind==='altitude'?'Een 3–4–5-driehoek. De hoogte vanuit de rechte hoek op de schuine zijde is 2,4: dezelfde oppervlakte 6 = ½ × 5 × 2,4.':'Een rechthoekige 3–4–5-driehoek. De rechte hoek ligt bij F. Bij hoek A is FP overstaand, AF aanliggend en AP de schuine zijde.';
  return <Canvas caption={caption}><Polygon points={[A,B,C]}/><Point p={A} name="A" below/><Point p={B} name={cos||iso||equil?'B':'F'} below/><Point p={C} name={cos||iso||equil?'C':'P'}/><Label p={[(A[0]+B[0])/2,270]}>{cos?'7':iso?'6':'4'}</Label><Label p={[(A[0]+C[0])/2-18,(A[1]+C[1])/2]}>{cos?'5':iso?'5':equil?'4':'5'}</Label><Label p={[(B[0]+C[0])/2+20,(B[1]+C[1])/2]}>{cos?'√39':iso?'5':equil?'4':'3'}</Label>{!cos&&!iso&&!equil&&<Right p={B} u={[-1,0]}/>} {(iso||equil||kind==='altitude')&&<><Line a={kind==='altitude'?B:C} b={H} color={orange} dashed/><Right p={H} u={kind==='altitude'?[.8,-.6]:[1,0]} v={kind==='altitude'?[.6,.8]:[0,-1]}/><Label p={kind==='altitude'?[331,181]:[H[0]+21,180]} color={orange}>{iso?'4':equil?'2√3':'2,4'}</Label></>}{cos&&<Label p={[125,220]} color={orange}>60°</Label>}</Canvas>;
 }
 if(kind==='line')return <Canvas caption="De rechte lijn l loopt voorbij A en B door. Het groene deel is lijnstuk AB; punt C ligt op de lijn, maar buiten het lijnstuk."><Line a={[25,150]} b={[455,150]} dashed/><Line a={[120,150]} b={[290,150]} color={mint}/><Point p={[120,150]} name="A"/><Point p={[290,150]} name="B"/><Point p={[400,150]} name="C"/><Label p={[445,180]}>l</Label></Canvas>;
 if(kind==='lines')return <Canvas caption="Twee lijnen in één vlak snijden elkaar in S. S ligt op beide lijnen. Voor lijnen in de ruimte moet die gemeenschappelijke ligging eerst worden vastgesteld."><Line a={[40,230]} b={[440,70]} color={mint}/><Line a={[80,70]} b={[400,230]} color={purple}/><Point p={[240,150]} name="S" below/></Canvas>;
 if(kind==='parallel')return <Canvas caption="De twee horizontale lijnen zijn evenwijdig. De gemarkeerde hoeken α zijn gelijk: overeenkomstige F-hoeken en verwisselende binnenhoeken (Z-hoeken)."><Line a={[35,100]} b={[445,100]} color={mint}/><Line a={[35,210]} b={[445,210]} color={mint}/><Line a={[140,260]} b={[330,40]} color={purple}/><Label p={[304,88]} color={orange}>α</Label><Label p={[252,128]} color={orange}>α</Label><Label p={[209,198]} color={orange}>α</Label><Label p={[55,87]}>l</Label><Label p={[55,236]}>m</Label></Canvas>;
 if(kind==='similarity')return <Canvas caption="Twee gelijkvormige rechthoekige driehoeken met zijden 3–4–5 en 6–8–10. De lengteschaal is 2; de oppervlaktefactor is 4."><Polygon points={[[40,220],[120,220],[120,160]]}/><Polygon points={[[240,230],[400,230],[400,110]]} color={purple}/><Label p={[80,248]}>4</Label><Label p={[138,197]}>3</Label><Label p={[63,181]}>5</Label><Label p={[320,258]}>8</Label><Label p={[420,177]}>6</Label><Label p={[298,156]}>10</Label><Label p={[235,60]} color={orange}>lengtes × 2 · oppervlaktes × 4</Label></Canvas>;
 if(kind==='area')return <Canvas caption="Parallellogram met basis b en loodrechte hoogte h. De hoogte staat loodrecht op de basis en is niet de schuine zijlengte. De oppervlakte is b × h."><Polygon points={[[70,230],[350,230],[410,90],[130,90]]}/><Line a={[130,90]} b={[130,230]} color={orange} dashed/><Right p={[130,230]}/><Label p={[215,261]}>b</Label><Label p={[109,165]} color={orange}>h</Label></Canvas>;
 if(kind==='trapezoid')return <Canvas caption="Trapezium: de evenwijdige zijden hebben lengten a en b; h is hun loodrechte afstand. De oppervlakte is ½(a + b)h."><Polygon points={[[70,240],[410,240],[325,90],[155,90]]}/><Line a={[325,90]} b={[325,240]} color={orange} dashed/><Right p={[325,240]}/><Label p={[240,75]}>a</Label><Label p={[240,273]}>b</Label><Label p={[345,172]} color={orange}>h</Label></Canvas>;
 if(kind==='rhombus')return <Canvas caption="Ruit: de diagonalen d₁ en d₂ staan loodrecht op elkaar en halveren elkaar. De oppervlakte is ½d₁d₂."><Polygon points={[[60,150],[240,30],[420,150],[240,270]]}/><Line a={[60,150]} b={[420,150]} color={purple}/><Line a={[240,30]} b={[240,270]} color={orange}/><Right p={[240,150]}/><Label p={[145,140]}>d₁</Label><Label p={[266,100]}>d₂</Label></Canvas>;
 if(kind==='perspective')return <Canvas caption="De spoorrails hebben dezelfde ruimtelijke richting. In dit perspectiefbeeld lopen ze naar verdwijnpunt V op de horizon. De echte rails blijven evenwijdig."><Line a={[25,90]} b={[455,90]} color={purple}/><Label p={[385,77]}>horizon</Label><Line a={[40,265]} b={[240,90]} color={mint}/><Line a={[440,265]} b={[240,90]} color={mint}/>{Array.from({length:10},(_,i)=>{const y=90+175/(1+i*.6),d=(y-90)*200/175;return <Line key={i} a={[240-d,y]} b={[240+d,y]} color="#829aa9"/>})}<Point p={[240,90]} name="V"/></Canvas>;
 if(kind==='circle'||kind==='thales')return <Canvas caption={kind==='thales'?'AB is een middellijn en P ligt op de cirkel. Daarom is ∠APB = 90°. M is het middelpunt.':'Cirkel met middelpunt M. MP is een straal r; AB is een middellijn met lengte 2r.'}><circle cx="240" cy="160" r="105" fill={mint+'0c'} stroke={mint} strokeWidth="2.5"/><Line a={[135,160]} b={[345,160]}/><Point p={[135,160]} name="A" below/><Point p={[345,160]} name="B" below/><Point p={[240,160]} name="M" below/><Point p={[240,55]} name="P"/>{kind==='thales'?<><Line a={[135,160]} b={[240,55]} color={purple}/><Line a={[345,160]} b={[240,55]} color={purple}/><Right p={[240,55]} u={[-Math.SQRT1_2,Math.SQRT1_2]} v={[Math.SQRT1_2,Math.SQRT1_2]}/></>:<><Line a={[240,160]} b={[240,55]} color={orange}/><Label p={[260,119]} color={orange}>r</Label></>}</Canvas>;
 if(kind==='sphere')return <Canvas caption="Vlakke hulpfiguur in een bol met straal 5. Een doorsnedevlak ligt 3 van M; de straal FP van de doorsnedecirkel is 4. Driehoek MFP is rechthoekig in F."><circle cx="240" cy="160" r="105" fill={mint+'0c'} stroke={mint} strokeWidth="2.5"/><Line a={[156,97]} b={[324,97]} color={purple}/><Line a={[240,160]} b={[240,97]} color={orange}/><Line a={[240,160]} b={[324,97]}/><Right p={[240,97]} v={[0,1]}/><Point p={[240,160]} name="M" below/><Point p={[240,97]} name="F"/><Point p={[324,97]} name="P"/><Label p={[221,136]}>3</Label><Label p={[284,85]}>4</Label><Label p={[291,145]}>5</Label></Canvas>;
 if(kind==='cylinder')return <Canvas caption="Rechte cirkelcilinder met straal r en hoogte h. De uitgerolde mantel is een rechthoek van 2πr bij h; voor de gesloten buitenkant komen er twee cirkelschijven bij."><ellipse cx="130" cy="85" rx="65" ry="25" fill={mint+'18'} stroke={mint} strokeWidth="2.5"/><ellipse cx="130" cy="235" rx="65" ry="25" fill="none" stroke={mint} strokeWidth="2.5"/><Line a={[65,85]} b={[65,235]} color={mint}/><Line a={[195,85]} b={[195,235]} color={mint}/><Line a={[130,85]} b={[195,85]} color={orange}/><Label p={[163,74]}>r</Label><Label p={[214,167]}>h</Label><rect x="285" y="85" width="140" height="150" fill={purple+'18'} stroke={purple} strokeWidth="2.5"/><Label p={[355,266]}>2πr</Label><Label p={[444,165]}>h</Label></Canvas>;
 if(kind==='net')return <Canvas caption="Een mogelijke kubusontvouwing: vier vierkanten naast elkaar, met één boven en één onder het tweede. Elk vlak heeft oppervlakte a²; samen 6a².">{[[65,115],[135,115],[205,115],[275,115],[135,45],[135,185]].map(([x,y],i)=><g key={i}><rect x={x} y={y} width="70" height="70" fill={(i===1?orange:mint)+'18'} stroke={ink} strokeWidth="2"/><Label p={[x+35,y+42]}>{i+1}</Label></g>)}<Label p={[380,154]}>6 × a²</Label></Canvas>;
 throw new Error('Onbekende vraagbaakfiguur: '+kind);
}
