import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BANK,CHECKS,QUESTIONS,type LearningEvent} from '../space-tent/app/model';
import {QuestionCard,CorrectAnswer,LearningView,LevelCheck} from '../space-tent/app/learning';
import QuestionFigure from '../space-tent/app/question-figure';
import Workbench from '../space-tent/app/workbench';
import ConstructionLab from '../space-tent/app/construction-lab';
import {CONSTRUCTION_TASKS} from '../space-tent/app/course-construction';
import Paper from '../space-tent/app/paper';
import CoursePaper from '../space-tent/app/course-paper';
import {APP_VERSION} from '../space-tent/app/version';
import {catalogue,matching,KIND_NAMES,ROLE_NAMES,type Kind,type Item} from './catalogue';
import '../space-tent/app/explanation-audio.css';
import '../space-tent/app/globals.css';
import '../space-tent/app/construction-selection.css';
import './review.css';
const BASE='/apps/ruimteklaar/test/';
function initial(){const p=new URLSearchParams(location.search);return catalogue.find(i=>i.kind===p.get('kind')&&i.id===p.get('id'))||catalogue[0]}
function Review(){
 const first=useMemo(initial,[]),[kind,setKind]=useState<Kind>(first.kind),[level,setLevel]=useState(''),[block,setBlock]=useState(''),[role,setRole]=useState(''),[query,setQuery]=useState(''),[item,setItem]=useState<Item|null>(first),[events,setEvents]=useState<LearningEvent[]>([]),[attempt,setAttempt]=useState(0),[reveal,setReveal]=useState(false),[notice,setNotice]=useState(''),[copy,setCopy]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[contextOverride,setContextOverride]=useState('');
 const live=useRef(true),requesting=useRef(false);const items=useMemo(()=>matching(kind,level,block,role,query),[kind,level,block,role,query]);const index=item?items.findIndex(i=>i.id===item.id&&i.kind===item.kind):-1;
 const verify=useCallback(async()=>{try{const r=await fetch(BASE+'session',{cache:'no-store',credentials:'same-origin'});if(!r.ok){location.replace(BASE);return false}const d=await r.json();if(d.authenticated!==true){location.replace(BASE);return false}if(live.current){setReady(true);setNotice('')}return true}catch{if(live.current){setReady(false);setNotice('De toegang kan niet worden gecontroleerd. Controleer je verbinding en probeer opnieuw.')}return false}},[]);
 useEffect(()=>{live.current=true;void verify();const timer=setInterval(()=>void verify(),60000);const focus=()=>void verify();const pageshow=(e:PageTransitionEvent)=>{if(e.persisted){setReady(false);void verify()}};window.addEventListener('focus',focus);window.addEventListener('pageshow',pageshow);return()=>{live.current=false;clearInterval(timer);window.removeEventListener('focus',focus);window.removeEventListener('pageshow',pageshow)}},[verify]);
 // Coalesce rapid navigation: WebKit limits history writes. Selecting an item remains immediate.
 useEffect(()=>{const timer=setTimeout(()=>{const p=new URLSearchParams();if(item){p.set('kind',item.kind);p.set('id',item.id)}try{history.replaceState(null,'',BASE+(p.size?'?'+p.toString():''))}catch{setNotice('De opgave is geopend. Gebruik Kopieer vraagverwijzing als de adresbalk niet wordt bijgewerkt.')}},250);return()=>clearTimeout(timer)},[item]);
 function storeSelection(next:Item|null){setItem(next);setEvents([]);setAttempt(n=>n+1);setReveal(false);setCopy('');setContextOverride('');}
 async function choose(next:Item|null){if(requesting.current)return;requesting.current=true;setBusy(true);try{if(await verify())storeSelection(next)}finally{requesting.current=false;setBusy(false)}}
 async function filters(k:Kind,l:string,b:string,r:string,q:string){if(requesting.current)return;requesting.current=true;setBusy(true);try{if(await verify()){setKind(k);setLevel(l);setBlock(b);setRole(r);setQuery(q);storeSelection(matching(k,l,b,r,q)[0]||null)}}finally{requesting.current=false;setBusy(false)}}
 // Only tab memory. This callback never touches localStorage or the ordinary save API.
 const save=useCallback(async(type:LearningEvent['type'],payload:Record<string,unknown>)=>{if(!await verify())return false;const event={id:crypto.randomUUID(),type,payload,at:Date.now()};setEvents(previous=>[...previous,event]);return true},[verify]);
 const back=()=>document.querySelector('.review-navigation')?.scrollIntoView({behavior:'smooth',block:'center'}),next=()=>void choose(items[(index+1)%items.length]||null);
 const q=item?.kind==='question'?QUESTIONS[item.id]:null,b=q?BANK.blocks.find(b=>b.id===q.block):undefined;
 const context=contextOverride||(item?.roles.includes('check')?'check':item?.roles.includes('probe')?'probe':item?.roles.includes('retest')?'retest':'practice');
 const checkId=q?Object.keys(CHECKS).find(k=>CHECKS[k].includes(q.id)):undefined;
 const group=q?(context==='check'?CHECKS[checkId||'']||[q.id]:context==='probe'?b?.probeIds||[q.id]:context==='retest'?b?.retestIds||[q.id]:b?.questionIds||[q.id]):[];
 const key=(item?item.kind+':'+item.id:'none')+':'+attempt+':'+context;
 async function copyReference(){if(!item)return;const text=`Spacetent · Ruimteklaar ${APP_VERSION} · testmodus 0.1\n${KIND_NAMES[item.kind]} · les ${item.level} · code ${item.id}\n${item.title}\nTestlink: ${location.origin}${BASE}?kind=${item.kind}&id=${encodeURIComponent(item.id)}\nOpmerking: `;setCopy(text);try{await navigator.clipboard.writeText(text);setNotice('Vraagverwijzing gekopieerd. Voeg je opmerking toe in het bestaande Kladblok.')}catch{setNotice('Selecteer en kopieer de verwijzing hieronder.')}}
 return <main className="app-shell review-shell"><header className="review-banner"><div><strong>TESTMODUS · Spacetent</strong><span>Ruimteklaar {APP_VERSION} · testmodus 0.1</span><p>Vrij onderzoeken — telt niet mee voor je voortgang. Testwerk verdwijnt bij herladen of wisselen van opgave.</p></div><form action={BASE+'logout'} method="post"><button type="submit">Uitloggen</button></form></header>
 <nav className="review-links"><a href="/apps/ruimteklaar/">Gewone leerroute</a><a href="/kladblok/" target="_blank" rel="noopener noreferrer">Wisik-Kladblok ↗</a></nav>
 <p className="review-notice" role="status">{notice}</p>{!ready?<section><h1>Toegang controleren</h1><button onClick={()=>void verify()}>Opnieuw proberen</button></section>:<>
 <section className="review-navigation" aria-label="Vrij opgaven kiezen"><div className="review-filters"><label>Onderdeel<select aria-label="Onderdeel" disabled={busy} value={kind} onChange={e=>void filters(e.target.value as Kind,'','','','')}>{Object.entries(KIND_NAMES).map(([k,n])=><option value={k} key={k}>{n} ({catalogue.filter(i=>i.kind===k).length})</option>)}</select></label><label>Les<select aria-label="Les" disabled={busy} value={level} onChange={e=>void filters(kind,e.target.value,'',role,query)}><option value="">Alle lessen</option>{[1,2,3,4,5,6,7].map(l=><option value={l} key={l}>{l===7?'Toplevel':'Les '+l}</option>)}</select></label>{kind==='question'&&<><label>Onderwerp<select aria-label="Onderwerp" disabled={busy} value={block} onChange={e=>void filters(kind,level,e.target.value,role,query)}><option value="">Alle onderwerpen</option>{BANK.blocks.filter(b=>!level||(b.level||1)===Number(level)).map(b=><option value={b.id} key={b.id}>{b.title}</option>)}</select></label><label>Vraagsoort<select aria-label="Vraagsoort" disabled={busy} value={role} onChange={e=>void filters(kind,level,block,e.target.value,query)}><option value="">Alle vraagsoorten</option>{Object.entries(ROLE_NAMES).map(([r,n])=><option value={r} key={r}>{n}</option>)}</select></label></>}</div>
 <form className="review-search" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void filters(kind,level,block,role,String(data.get('zoek')||''))}}><label>Zoek op code of tekst<input type="search" name="zoek" aria-label="Zoek op code of tekst" defaultValue={query} key={kind} placeholder="Bijvoorbeeld loodvoet of een vraagcode"/></label><button type="submit" disabled={busy}>Zoeken</button><button type="button" disabled={busy} onClick={()=>{void filters(kind,'','','','');const el=document.querySelector<HTMLInputElement>('[name="zoek"]');if(el)el.value=''}}>Filters wissen</button></form>
 <label className="review-picker">Kies een opgave<select aria-label="Kies een opgave" disabled={busy||!items.length} value={item&&index>=0?item.id:''} onChange={e=>void choose(items.find(i=>i.id===e.target.value)||null)}>{!items.length&&<option value="">Geen resultaten</option>}{items.map(i=><option value={i.id} key={i.id}>{i.id} · {i.title.length>125?i.title.slice(0,125)+'…':i.title}</option>)}</select></label>
 <div className="review-toolbar"><button disabled={busy||index<=0} onClick={()=>void choose(items[index-1])}>Vorige opgave</button><span>{items.length?index+1:0} / {items.length}</span><button disabled={busy||index<0||index>=items.length-1} onClick={next}>Volgende / overslaan</button><button disabled={busy||!item} onClick={()=>void choose(item)}>Opnieuw testen</button></div></section>
 {item?<><section className="review-metadata"><h1>{item.id}</h1><p>Les {item.level} · {KIND_NAMES[item.kind]}{item.roles.length?' · '+item.roles.map(r=>ROLE_NAMES[r]).join(' / '):''}</p>{q&&<label>Studentweergave<select aria-label="Studentweergave" value={context} onChange={e=>{setContextOverride(e.target.value);setAttempt(n=>n+1);setReveal(false);setEvents([])}}>{(item.roles.length?item.roles:['practice']).map(r=><option value={r} key={r}>{ROLE_NAMES[r]}</option>)}</select></label>}<div className="review-toolbar"><button onClick={()=>void copyReference()}>Kopieer vraagverwijzing</button>{q&&<button aria-expanded={reveal} onClick={()=>setReveal(s=>!s)}>{reveal?'Verberg antwoord en uitwerking':'Toon antwoord en uitwerking'}</button>}</div>{copy&&<textarea className="review-reference" aria-label="Vraagverwijzing" readOnly value={copy}/>}</section>
 {reveal&&q&&<section className="review-answer"><h2>Controleweergave voor de maker</h2><CorrectAnswer question={q}/><p>{q.explanation}</p><QuestionFigure question={q} reveal/></section>}
 <section className="review-content" data-review-kind={item.kind} data-review-id={item.id}>
 {q&&<QuestionCard key={key} question={q} context={context} sessionId={'review-'+key} save={save} onNext={next} number={Math.max(1,group.indexOf(q.id)+1)} total={group.length||1} deferOnAnswer={context==='practice'&&b?.misconception.trigger.qid===q.id?b.misconception.trigger.wrongAnswer:undefined} guided={context==='retest'}/>}
 {item.kind==='construction'&&(item.id.startsWith('atelier-')?<Workbench key={key} initialVariant={item.id==='atelier-1'?1:0} save={save} onBack={back}/>:<ConstructionLab key={key} task={CONSTRUCTION_TASKS.find(t=>t.id===item.id)!} events={events} save={save} onBack={back}/>)}
 {item.kind==='block'&&<LearningView key={key} block={BANK.blocks.find(b=>b.id===item.id)!} events={events} save={save} onBack={back} onDone={next}/>}
 {item.kind==='check'&&<LevelCheck key={key} checkKey={item.id} events={events} save={save} onBack={back}/>}
 {item.kind==='paper'&&(item.id==='1'?<Paper key={key} save={save} onBack={back} alreadyDone={false}/>:<CoursePaper key={key} paperKey={item.id} save={save} onBack={back} alreadyDone={false}/>)}
 </section><p className="review-footnote">Knoppen en feedback hierboven zijn de echte oefencomponenten. ‘Mijn route’, ‘opslaan’ en ‘XP’ daarin horen in deze testomgeving uitsluitend bij de tijdelijke testpoging. De balk bovenaan blijft de vrije navigatie.</p></>:<p role="status">Geen opgaven gevonden. Wis de filters om opnieuw te kiezen.</p>}
 </>}</main>
}
createRoot(document.getElementById('root')!).render(<Review/>);
