import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';import os from 'node:os';import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {randomBytes} from 'node:crypto';
import {handleTestRequest,BASE} from './server.mjs';
import {assets} from './generated-assets.mjs';
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../..'),space=path.join(repo,'tools/space-tent'),out=path.join(here,'.browser');fs.mkdirSync(out,{recursive:true});
const data=JSON.parse(fs.readFileSync(path.join(space,'app/content.json'))),course=JSON.parse(fs.readFileSync(path.join(space,'app/course-content.json'))),tasks=JSON.parse(fs.readFileSync(path.join(space,'app/construction-tasks.json'))).tasks;
const questions=[...data.questions,...course.questions],blocks=[...data.blocks,...course.blocks];
const env={RUIMTEKLAAR_TEST_PASSWORD:randomBytes(24).toString('base64url'),RUIMTEKLAAR_TEST_SESSION_SECRET:randomBytes(40).toString('base64url'),RUIMTEKLAAR_TEST_TURNSTILE_SITE_KEY:'0x4AAA'+randomBytes(20).toString('hex'),RUIMTEKLAAR_TEST_TURNSTILE_SECRET_KEY:randomBytes(30).toString('hex')};
const results=[],errors=[],traces=[];let origin='',browser,activePage,activeEnvironment,enabled=true,writes=[];
const certDir=fs.mkdtempSync(path.join(os.tmpdir(),'review-https-'));
execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-keyout',path.join(certDir,'key.pem'),'-out',path.join(certDir,'cert.pem'),'-days','1','-nodes','-subj','/CN=localhost'],{stdio:'ignore'});
const server=https.createServer({key:fs.readFileSync(path.join(certDir,'key.pem')),cert:fs.readFileSync(path.join(certDir,'cert.pem'))},async(req,res)=>{
 try{
  const url=new URL(req.url,origin);if(req.method==='POST')writes.push(url.pathname);
  if(url.pathname===BASE.slice(0,-1)||url.pathname.startsWith(BASE)){
   const chunks=[];for await(const chunk of req)chunks.push(chunk);
   const request=new Request(url,{method:req.method,headers:req.headers,...(['GET','HEAD'].includes(req.method)?{}:{body:Buffer.concat(chunks)})});
   const response=await handleTestRequest(request,enabled?env:{},assets,{fetcher:async()=>Response.json({success:true,hostname:url.hostname,action:'ruimteklaar_test_login'})});
   traces.push({method:req.method,path:url.pathname,status:response.status});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return;
  }
  let file=url.pathname.startsWith('/apps/ruimteklaar/')?path.join(space,'.space-dist',url.pathname.slice('/apps/ruimteklaar/'.length)||'index.html'):path.join(repo,'public',url.pathname);if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');
  if(!fs.existsSync(file)){res.writeHead(404);res.end('not found');return;}
  res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.m4a')?'audio/mp4':'text/html'});res.end(fs.readFileSync(file));
 }catch(e){errors.push('test server: '+e.message);res.writeHead(500);res.end('Test server error');}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='https://127.0.0.1:'+server.address().port;
try{for(const c of [{name:'chromium-desktop',engine:chromium,width:1280,mobile:false},{name:'chromium-mobile',engine:chromium,width:390,mobile:true},{name:'webkit-mobile',engine:webkit,width:390,mobile:true}]){
 enabled=true;writes=[];traces.length=0;
 browser=await c.engine.launch({headless:true});const context=await browser.newContext({viewport:{width:c.width,height:900},isMobile:c.mobile,hasTouch:c.mobile,ignoreHTTPSErrors:true});
 // Only the third-party challenge is simulated. Login, cookies, redirects and all app assets use real HTTPS.
 await context.route('https://challenges.cloudflare.com/**',async route=>{await route.fulfill({status:200,contentType:'text/javascript',body:`document.querySelectorAll('form').forEach(f=>{const x=document.createElement('input');x.type='hidden';x.name='cf-turnstile-response';x.value='browser-test-bot-proof';f.appendChild(x)})`});});
 const page=await context.newPage();activePage=page;activeEnvironment=c.name;page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(c.name+': '+e.message));
 await page.goto(origin+'/apps/ruimteklaar/');await page.getByRole('button',{name:'Open het oefenatelier',exact:false}).waitFor();await page.evaluate(()=>localStorage.setItem('review-learner-sentinel','must-not-change'));const before=await page.evaluate(()=>JSON.stringify({...localStorage}));
 await page.goto(origin+BASE+'app.js');assert.ok((await page.textContent('body')).includes('Aanmelden vereist'));
 await page.goto(origin+BASE);await page.screenshot({path:path.join(out,c.name+'-login.png'),fullPage:true});await page.getByLabel('Wachtwoord',{exact:true}).fill('intentionally-wrong-password');await page.getByRole('button',{name:'Open testmodus',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.locator('#root').count(),0);
 await page.getByLabel('Wachtwoord',{exact:true}).fill(env.RUIMTEKLAAR_TEST_PASSWORD);await page.getByRole('button',{name:'Open testmodus',exact:true}).click();await page.getByLabel('Onderdeel',{exact:true}).waitFor();assert.equal(await page.locator('.review-banner').count(),1);
 const pick=async id=>{await page.getByLabel('Kies een opgave',{exact:true}).selectOption(id);await page.locator(`.review-content[data-review-id="${id}"]`).waitFor();await page.waitForFunction(()=>!document.querySelector('[aria-label="Kies een opgave"]').disabled)};
 // Every question is accessible, in unchanged source order, without doing another question.
 assert.equal(await page.getByLabel('Kies een opgave',{exact:true}).locator('option').count(),questions.length);
 for(const q of questions){await pick(q.id);assert.equal((await page.locator('.review-content .question-prompt').innerText()).trim(),q.prompt.trim());assert.equal(await page.locator('.review-answer').count(),0);assert.equal(await page.locator('.review-content .feedback-panel').count(),0)}
 results.push({environment:c.name,scope:'all questions',count:questions.length,checks:'free selection; original prompt; no automatic answer reveal; no prerequisite route'});
 const numeric=questions.find(q=>q.type==='numeric'&&blocks.some(b=>b.questionIds.includes(q.id)));await pick(numeric.id);await page.getByRole('button',{name:'Toon antwoord en uitwerking',exact:true}).click();await page.locator('.review-answer .correct-answer').waitFor();await page.getByRole('button',{name:'Verberg antwoord en uitwerking',exact:true}).click();await page.getByLabel('Jouw berekende uitkomst',{exact:true}).fill(numeric.answer[0]);if(numeric.working)await page.locator('.review-content textarea').fill('Controle van de originele berekening in de testmodus.');await page.getByRole('button',{name:'Antwoord vastleggen',exact:false}).click();await page.locator('.review-content .feedback-panel').waitFor();
 assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage})),before);
 await page.getByRole('button',{name:'Opnieuw testen',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.numeric-input')?.value==='');
 await page.getByLabel('Vraagsoort',{exact:true}).selectOption('probe');await page.waitForFunction(()=>!document.querySelector('[aria-label="Kies een opgave"]').disabled);assert.ok(await page.getByLabel('Kies een opgave',{exact:true}).locator('option').count()>0);
 await page.getByLabel('Vraagsoort',{exact:true}).selectOption('check');await page.waitForFunction(()=>!document.querySelector('[aria-label="Kies een opgave"]').disabled);const checkQ=questions.find(q=>Object.values({'1':data.checkpointIds,...course.checks}).flat().includes(q.id)&&q.type==='numeric');await pick(checkQ.id);await page.getByLabel('Jouw berekende uitkomst',{exact:true}).fill(checkQ.answer[0]);if(checkQ.working)await page.locator('.review-content textarea').fill('Testberekening met voldoende tekst voor de originele invoer.');await page.getByRole('button',{name:'Antwoord vastleggen',exact:false}).click();await page.locator('.review-content .feedback-panel.neutral').waitFor();assert.equal(await page.locator('.review-content .correct-answer').count(),0);
 await page.getByLabel('Onderdeel',{exact:true}).selectOption('construction');await page.waitForFunction(()=>!document.querySelector('[aria-label="Kies een opgave"]').disabled);assert.equal(await page.getByLabel('Kies een opgave',{exact:true}).locator('option').count(),tasks.length+2);
 for(const t of [...tasks,...[0,1].map(v=>({id:'atelier-'+v,edges:['AB']}))]){await pick(t.id);const [a,b]=t.edges[0],point=n=>page.locator('.selection-controls .point-tray').getByRole('button',{name:n,exact:true});for(const p of [a,b]){if(c.mobile)await point(p).tap();else await point(p).click()}await page.locator('[data-action="extend"]').click();await page.waitForFunction(()=>document.querySelectorAll('.drawing-panel .drawn-line').length===1);await page.locator('.drawing-footer button').click();await page.waitForFunction(()=>document.querySelectorAll('.drawing-panel .drawn-line').length===0)}
 const shapes=[];for(const id of ['atelier-0','atelier-1']){await pick(id);shapes.push(await page.locator('.geometry-stage svg').first().innerHTML())}assert.notEqual(shapes[0],shapes[1],'Directly selected atelier variants differ');
 results.push({environment:c.name,scope:'all constructions',count:tasks.length+2,checks:'free choice including both atelier variants and summit; point selection; direct extend; undo; no learner save'});
 for(const [kind,ids] of [['block',blocks.map(b=>b.id)],['check',Object.keys({'1':data.checkpointIds,...course.checks})],['paper',['1',...Object.keys(course.papers).filter(k=>k!=='1')]]]){await page.getByLabel('Onderdeel',{exact:true}).selectOption(kind);await page.waitForFunction(()=>!document.querySelector('[aria-label="Kies een opgave"]').disabled);for(const id of ids){await pick(id);assert.ok((await page.locator('.review-content').innerText()).length>70)}results.push({environment:c.name,scope:kind,count:ids.length,checks:'all original components accessible without route or waiting period'})}
 // Deep links identify one question but still require authentication.
 await page.goto(origin+BASE+'?kind=question&id='+encodeURIComponent(numeric.id));await page.locator(`.review-content[data-review-id="${numeric.id}"]`).waitFor();await page.getByRole('button',{name:'Toon antwoord en uitwerking',exact:true}).click();await page.screenshot({path:path.join(out,c.name+'.png'),fullPage:true});
 for(const width of c.mobile?[320,390]:[760,1280]){await page.setViewportSize({width,height:900});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth+1,null,{timeout:2000}).catch(async()=>{const d=await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,scale:visualViewport?.scale,elements:Array.from(document.querySelectorAll('body,body *')).map(e=>({tag:e.tagName,classes:String(e.className),scroll:e.scrollWidth,client:e.clientWidth,right:e.getBoundingClientRect().right,left:e.getBoundingClientRect().left})).filter(e=>e.scroll>e.client+1||e.right>innerWidth+1||e.left< -1).slice(0,40)}));throw new Error('Responsive overflow '+JSON.stringify(d))});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal overflow at '+width)}
 assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage})),before);assert.ok(writes.every(p=>p===BASE+'login'||p===BASE+'logout'),'No learner answers sent over network');
 await page.getByRole('button',{name:'Uitloggen',exact:true}).click();await page.getByLabel('Wachtwoord',{exact:true}).waitFor();await page.goto(origin+BASE+'app.js');assert.ok((await page.textContent('body')).includes('Aanmelden vereist'));enabled=false;await page.goto(origin+BASE+'?kind=question&id='+numeric.id);assert.ok((await page.textContent('body')).includes('nog niet geactiveerd'));assert.equal(await page.locator('.review-content').count(),0);
 results.push({environment:c.name,scope:'isolation and access',checks:'wrong password; login; manual reveal; original check feedback; filters; deep link; logout; no-store; disabled mode; unchanged localStorage; no answer requests; narrow layout'});
 await context.close();await browser.close();browser=null;
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({status:'passed',results,errors,limitations:['Browser automation, not a physical iPhone test.','Turnstile success/failure responses and widget simulated in browser tests; real activation requires Cloudflare settings.','No empirical usability study or independent penetration test.']},null,2));console.log(JSON.stringify({status:'passed',groups:results.length,questionViews:questions.length*3},null,2));}catch(e){if(activePage){await activePage.screenshot({path:path.join(out,(activeEnvironment||'browser')+'-failure.png'),fullPage:true}).catch(()=>{});}fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({status:'failed',environment:activeEnvironment,completed:results,error:e.message,pageErrors:errors,traces,url:activePage?.url(),overflow:await activePage?.evaluate(()=>Array.from(document.querySelectorAll('body *')).map(e=>({tag:e.tagName,classes:e.className,rect:e.getBoundingClientRect().toJSON()})).filter(e=>e.rect.right>innerWidth+1||e.rect.left< -1).slice(0,25)).catch(()=>[]),document:await activePage?.content().then(s=>s.slice(0,1500)).catch(()=>null)},null,2));throw e;}finally{if(browser)await browser.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(certDir,{recursive:true,force:true})}
