'use client';
import {newEventId} from './identity';
import {useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {ArrowLeft,ArrowRight,Check,CheckCircle2,Lightbulb,RotateCcw,Target,BookOpen,ScanEye} from 'lucide-react';
import Geometry from './geometry';
import CourseFigure from './course-figure';
import {numericValue} from './numeric';
import InsightFigure from './insight-figure';
import QuestionFigure from './question-figure';
import {BANK,QUESTIONS,CHECKS,checkAttempts,checkGroup,blocksForLevel,pointsForQuestion,correctAnswer,deriveProgress,type Question,type Block,type LearningEvent} from './model';
import {resumeBlock,isMisconceptionTrigger,supportsMisconception} from './diagnostic';
import type {SaveEvent} from './workbench';
export function shuffled<T>(a:T[],seed:string):T[]{let s=[...seed].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,17);const copy=[...a];for(let i=copy.length-1;i>0;i--){s=(1664525*s+1013904223)>>>0;const j=s%(i+1);[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
export function CorrectAnswer({question:q}:{question:Question}){
 const alternatives=q.type==='points'&&!!q.acceptAny?.length;
 const label=alternatives?(q.selectCount===1?'Goed antwoord · één van deze punten:':`Goed antwoord · kies ${q.selectCount||1} van deze punten:`):'Goed antwoord:';
 const text=q.type==='numeric'?`${q.decimals!==undefined?Number(q.answer[0]).toLocaleString('nl-NL',{minimumFractionDigits:q.decimals,maximumFractionDigits:q.decimals}):q.answer[0]} ${q.unit||''}`:q.type==='choice'?(q.options||[]).filter(o=>q.answer.includes(o.id)).map(o=>o.text).join(' / '):(alternatives?q.acceptAny!.join(', '):q.answer.join(' én '));
 return <div className="correct-answer"><CheckCircle2 aria-hidden="true"/><p><strong>{label}</strong><span>{text}</span></p></div>
}
export function QuestionCard({question:q,context='practice',sessionId,save,onNext,number,total,seen=false,deferOnAnswer,guided=false}:{question:Question;context?:string;sessionId:string;save:SaveEvent;onNext:(correct:boolean,answer:string[])=>void;number:number;total:number;seen?:boolean;deferOnAnswer?:string;guided?:boolean}){
 const [working,setWorking]=useState('');
 const [answer,setAnswer]=useState<string[]>([]),[hint,setHint]=useState(false),[rotated,setRotated]=useState(false),[submitted,setSubmitted]=useState(false),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [seenBefore]=useState(seen);
 const hiddenFeedback=context==='probe'||context==='check'||(submitted&&!!deferOnAnswer&&answer.includes(deferOnAnswer));const options=useMemo(()=>shuffled(q.options||[],sessionId+q.id),[q.id,sessionId]);
 const showCorrectAnswer=submitted&&!hiddenFeedback;
 const correctPoints=q.acceptAny?.length?q.acceptAny:q.answer;
 const result=correctAnswer(q,answer),enough=answer.length===(q.type==='points'?(q.selectCount||q.answer.length):1)&&(q.type!=='numeric'||numericValue(answer[0])!==null)&&(!q.working||working.trim().length>=8);
 function selectPoint(p:string){if(submitted)return;const max=q.selectCount||q.answer.length;setAnswer(a=>a.includes(p)?a.filter(x=>x!==p):a.length>=max?[p]:[...a,p]);}
 async function submit(){if(!enough)return;setSubmitted(true);setBusy(true);setError('');const ok=await save('answer',{questionId:q.id,answer,helped:hint||guided||rotated,context,sessionId,...(q.working?{working}: {})});setBusy(false);setSaved(ok);if(!ok)setError('Je antwoord is nog niet opgeslagen. Probeer het opnieuw.');}
 return <div className="exercise"><div className="exercise-heading"><span className="eyebrow">{context==='check'?'LEVELCHECK':context==='probe'?'EVEN PRECIES KIJKEN':context==='retest'?'NIEUWE TOEPASSING':'ZELF AAN DE SLAG'}</span><span className="step-counter">{number} / {total}</span></div><Progress value={(number-1)/total*100} aria-label="Voortgang binnen deze oefenreeks"/><h2 className="question-prompt">{q.prompt}</h2><div className="exercise-layout"><div className="exercise-figure"><QuestionFigure key={q.id} question={q} reveal={submitted&&!hiddenFeedback} answer={answer} selectable={q.type==='points'?pointsForQuestion(q):[]} onPoint={selectPoint} allowRotate={(context==='practice'||context==='retest')&&q.block!=='projection'} onExplore={()=>{if(!submitted)setRotated(true)}}/></div><div className="answer-area">{q.type==='numeric'?<label className="numeric-label">Jouw uitkomst {q.unit&&`(${q.unit})`}<input className="numeric-input" inputMode="decimal" autoComplete="off" value={answer[0]||''} disabled={submitted} onChange={e=>setAnswer(e.target.value?[e.target.value]:[])} aria-label="Jouw berekende uitkomst"/><small>Een komma of punt kan allebei. Exact mag ook: 4*sqrt(2) of 8/3.</small></label>:q.type==='choice'?<RadioGroup value={answer[0]||''} onValueChange={v=>setAnswer([v])} disabled={submitted} aria-label="Jouw antwoord">{options.map(o=><label key={o.id} className={'answer-option '+(answer.includes(o.id)?'selected ':'')+(showCorrectAnswer&&q.answer.includes(o.id)?'answer-correct':'')}><RadioGroupItem value={o.id}/><span>{o.text}{showCorrectAnswer&&q.answer.includes(o.id)&&<small className="answer-verdict"><Check aria-hidden="true"/>Goed antwoord</small>}</span></label>)}</RadioGroup>:<><p>Kies {q.selectCount||q.answer.length} {(q.selectCount||q.answer.length)===1?'punt':'punten'}. De volgorde maakt niet uit.</p><div className="point-tray">{pointsForQuestion(q).map(k=><Button key={k} variant="outline" className={'point-tag '+(answer.includes(k)?'active ':'')+(showCorrectAnswer&&correctPoints.includes(k)?'answer-correct':'')} aria-pressed={answer.includes(k)} disabled={submitted} onClick={()=>selectPoint(k)}>{k}</Button>)}</div><p className="muted">Gekozen: {answer.join(' en ')||'nog geen punt'}</p></>}
 {q.working&&<label className="working-label">Jouw aanpak en berekening<textarea value={working} disabled={submitted} maxLength={2000} onChange={e=>setWorking(e.target.value)} placeholder="Welke driehoek, loodlijn of formule gebruik je, en waarom?"/><small>De uitkomst wordt automatisch nagekeken. Je redenering vergelijk je zelf met de uitwerking.</small></label>}
 {!submitted&&<div className="question-actions"><Button onClick={submit} disabled={!enough||busy}>Antwoord vastleggen <ArrowRight/></Button>{!hiddenFeedback&&<Button variant="ghost" onClick={()=>setHint(true)}><Lightbulb/>Aanwijzing</Button>}</div>}{hint&&<div className="hint-box">{q.hint}</div>}
 {submitted&&<div className={'feedback-panel '+(hiddenFeedback?'neutral':result?'correct':'reflect')} role="status">{hiddenFeedback?<><span>Antwoord vastgelegd.</span><p>Je krijgt de terugkoppeling na deze reeks.</p></>:<><h3>{result?'Dat klopt.':'Bekijk de redenering.'}</h3>{!result&&<CorrectAnswer question={q}/>}<p>{q.explanation}</p>{result&&<span className="evidence-label">{hint||seenBefore||guided||rotated?'Geoefend met steun of na herhaling':'Correct bij je eerste poging'}</span>}</>}{error&&<p role="alert">{error}</p>}{saved?<Button onClick={()=>onNext(result,answer)}>Verder <ArrowRight/></Button>:<Button onClick={submit} disabled={busy}>{busy?'Opslaan…':'Opnieuw opslaan'}</Button>}</div>}
 </div></div></div>
}
export function LearningView({block,events,save,onBack,onDone}:{block:Block;events:LearningEvent[];save:SaveEvent;onBack:()=>void;onDone:()=>void}){
 const [resume]=useState(()=>resumeBlock(block,events));const [sessionId]=useState(()=>resume.sessionId||newEventId());
 const [stage,setStage]=useState<'theory'|'practice'|'probe'|'repair'|'retest'|'summary'|'complete'>(resume.stage),[theory,setTheory]=useState(0),[index,setIndex]=useState(resume.index),[probeIndex,setProbeIndex]=useState(resume.probeIndex),[probeAnswers,setProbeAnswers]=useState<string[][]>(resume.probeAnswers),[retestIndex,setRetestIndex]=useState(resume.retestIndex),[supported,setSupported]=useState(resume.supported),[retestSuccess,setRetestSuccess]=useState<boolean[]>(resume.retestSuccess),[finishing,setFinishing]=useState(false),[saveError,setSaveError]=useState(false);
 const progress=deriveProgress(events),q=stage==='probe'?QUESTIONS[block.probeIds[probeIndex]]:stage==='retest'?QUESTIONS[block.retestIds[retestIndex]]:QUESTIONS[block.questionIds[index]];
 async function completeBlock(){setFinishing(true);const ok=await save('block',{blockId:block.id});setFinishing(false);setSaveError(!ok);if(ok)setStage('summary')}
 function nextMain(){if(index<block.questionIds.length-1){setIndex(index+1);setStage('practice')}else void completeBlock()}
 function mainAnswered(correct:boolean,answer:string[]){if(!correct&&isMisconceptionTrigger(block,q.id,answer)){setProbeAnswers([]);setProbeIndex(0);setStage('probe')}else nextMain()}
 function probeAnswered(_:boolean,answer:string[]){const all=[...probeAnswers,answer];setProbeAnswers(all);if(probeIndex+1<block.probeIds.length)setProbeIndex(probeIndex+1);else{setSupported(supportsMisconception(block,all));setStage('repair')}}
 function retestAnswered(ok:boolean){setRetestSuccess(s=>[...s,ok]);if(retestIndex+1<block.retestIds.length)setRetestIndex(retestIndex+1);else nextMain()}
 const t=block.theory[theory];const answered=block.questionIds.filter(id=>progress.evidence[id]?.correct),independent=block.questionIds.filter(id=>progress.evidence[id]?.independent);
 return <section className="learning-view"><div className="section-top"><Button variant="ghost" onClick={onBack}><ArrowLeft/>Mijn route</Button><span className="eyebrow">LEVEL {String(block.level||1).padStart(2,'0')} · BLOK {blocksForLevel(block.level||1).findIndex(b=>b.id===block.id)+1}</span></div>
 {stage==='theory'&&<><div className="lesson-title"><span className="pill"><BookOpen/>INZICHT OPBOUWEN</span><h1 className="page-title">{block.title}</h1><p className="intro">{block.subtitle}</p></div><div className="theory-layout"><div className="theory-copy"><span className="step-counter">Inzicht {theory+1} van {block.theory.length}</span><h2>{t.title}</h2><p>{t.text}</p><div className="question-actions"><Button onClick={()=>{if(theory<block.theory.length-1)setTheory(theory+1);else{setIndex(0);setStage('practice')}}}>{theory<block.theory.length-1?'Volgend inzicht':'Zelf proberen'}<ArrowRight/></Button>{theory>0&&<Button variant="ghost" onClick={()=>setTheory(theory-1)}>Vorige</Button>}</div></div><div className="theory-figure">{t.scene?<CourseFigure key={theory} scene={t.scene}/>:t.example?<InsightFigure key={theory} example={t.example}/>:<Geometry highlights={t.highlights} planes={t.planes} caption="Onderzoek dezelfde kubus vanuit een andere kijkrichting."/>}</div></div><div className="reflection-prompt"><ScanEye/><p>Leg in je eigen woorden uit wat uit de gegevens volgt en wat de tekening alleen suggereert. Gebruik de figuur om je redenering te onderzoeken.</p></div></>}
 {(stage==='practice'||stage==='probe'||stage==='retest')&&q&&<QuestionCard key={sessionId+q.id+stage} question={q} sessionId={sessionId} context={stage==='practice'?'practice':stage} save={save} onNext={stage==='probe'?probeAnswered:stage==='retest'?retestAnswered:mainAnswered} number={(stage==='probe'?probeIndex:stage==='retest'?retestIndex:index)+1} total={stage==='probe'?block.probeIds.length:stage==='retest'?block.retestIds.length:block.questionIds.length} seen={!!progress.evidence[q.id]} deferOnAnswer={stage==='practice'&&q.id===block.misconception.trigger.qid?block.misconception.trigger.wrongAnswer:undefined} guided={stage==='retest'}/>}
 {stage==='repair'&&<div className="repair-view"><span className="pill"><Target/>GERICHT VERDER</span><h1 className="page-title">{supported?'We zien hetzelfde denkpatroon.':'We maken het onderscheid helder.'}</h1><p className="intro">{supported?`Je antwoorden ondersteunen dit vermoeden: ${block.misconception.label}.`:'Je antwoorden geven geen eenduidige bevestiging van het vermoeden. We bekijken het kernidee en toetsen het daarna opnieuw.'}</p><div className="theory-layout"><div className="theory-copy"><h2>{block.repair.title}</h2><p>{block.repair.text}</p><Button onClick={()=>{setRetestIndex(0);setRetestSuccess([]);setStage('retest')}}>Een nieuwe situatie proberen <ArrowRight/></Button></div><div className="theory-figure">{block.repair.scene?<CourseFigure scene={block.repair.scene}/>:block.repair.example?<InsightFigure example={block.repair.example}/>:<Geometry highlights={block.repair.highlights} planes={block.repair.planes}/>}</div></div><div className="diagnostic-review"><h2>Terug naar je antwoorden</h2>{[block.questionIds[index],...block.probeIds.filter((id,i)=>!correctAnswer(QUESTIONS[id],probeAnswers[i]||[]))].map(id=><article key={id}><h3>{QUESTIONS[id].prompt}</h3><CorrectAnswer question={QUESTIONS[id]}/><QuestionFigure question={QUESTIONS[id]} reveal/><p>{QUESTIONS[id].explanation}</p></article>)}</div><p className="muted">Een goede herstelvraag laat zien dat de uitleg nu helpt. Later is nog een zelfstandige controle nodig.</p></div>}
 {stage==='complete'&&<div className="block-summary"><h2>Je oefenreeks is compleet.</h2><p>Leg de afronding vast om je samenvatting te bekijken.</p><Button onClick={completeBlock} disabled={finishing}>Blok afronden</Button></div>}{saveError&&<div className="error-banner" role="alert">De afronding is nog niet opgeslagen. <Button onClick={completeBlock} disabled={finishing}>Opnieuw opslaan</Button></div>}
 {stage==='summary'&&<div className="block-summary"><div className="achievement-mark"><CheckCircle2/></div><span className="eyebrow">BLOK AFGEROND</span><h1 className="page-title">Weer een stukje verder.</h1><h2>{block.title}</h2><div className="summary-counts"><div><strong>{independent.length}</strong><span>zelfstandig bij de eerste poging</span></div><div><strong>{answered.length-independent.length}</strong><span>goed na hulp of herhaling</span></div></div><p>{independent.length===block.questionIds.length?'Je beantwoordde alle vragen direct goed. De levelcheck onderzoekt straks of het ook lukt zonder tussentijdse feedback.':`${block.questionIds.length-answered.length>0?`${block.questionIds.length-answered.length} vraag${block.questionIds.length-answered.length===1?' vraagt':'vragen vragen'} nog oefening. `:''}De vragen waarbij je hulp nodig had komen terug in gericht oefenen.`}</p>{probeAnswers.length>0&&<div className="hint-box"><strong>{supported?'Vermoeden ondersteund door de controlevragen.':'Vermoeden niet eenduidig bevestigd.'}</strong><p>{retestSuccess.length&&retestSuccess.every(Boolean)?'De nieuwe herstelvragen gingen goed. Het onderwerp blijft op de herhaallijst voor een latere zelfstandige toepassing.':'Dit onderscheid vraagt nog oefening. Je kunt de uitleg en een gerichte reeks opnieuw openen.'}</p></div>}<div className="question-actions"><Button onClick={onDone}>Volgende stap <ArrowRight/></Button><Button variant="outline" onClick={onBack}>Voor nu afronden</Button></div><p className="muted">Je voortgang is bewaard. Gebruik de voortgangopties om op een ander apparaat verder te gaan.</p></div>}
 </section>
}
export function LevelCheck({events,save,onBack,checkKey='1'}:{events:LearningEvent[];save:SaveEvent;onBack:()=>void;checkKey?:string}){
 const [attempt]=useState(()=>{const last=checkAttempts(events,checkKey).at(-1);return last});
 const [sessionId,setSessionId]=useState(()=>attempt?.sessionId||newEventId()),[started,setStarted]=useState(!!attempt);
 const ids=useMemo(()=>shuffled(CHECKS[checkKey]||[],sessionId),[checkKey,sessionId]);
 const [results,setResults]=useState<{id:string;correct:boolean;answer:string[];working?:string}[]>(()=>ids.flatMap(id=>{const e=attempt?.rows.find(e=>e.payload.questionId===id);return e?[{id,correct:correctAnswer(QUESTIONS[id],e.payload.answer),answer:e.payload.answer,working:e.payload.working}]:[]}));
 const index=ids.findIndex(id=>!results.some(r=>r.id===id)),finished=ids.length>0&&index<0,allCorrect=finished&&results.every(r=>r.correct),summit=checkKey.startsWith('7');
 return <section><div className="section-top"><Button variant="ghost" onClick={onBack}><ArrowLeft/>Mijn route</Button><span className="eyebrow">{summit?`TOPLEVEL · PROEF ${checkKey.slice(1).toUpperCase()}`:`LEVEL ${checkKey} · ZELFSTANDIGE CHECK`}</span></div>{!started?<div className="check-intro"><span className="pill"><Target/>ZONDER HINTS</span><h1 className="page-title">Laat zien wat je kunt.</h1><p>{ids.length} gemengde vragen. Kies zelf je aanpak. Je krijgt de volledige terugkoppeling na deze reeks; tussentijds zijn er geen aanwijzingen of draaibare figuren.</p><p>Alle vragen moeten goed zijn. Constructies en de controle van je redeneringen op papier horen afzonderlijk bij de afronding. Gebruik een rekenmachine, potlood en geodriehoek.</p>{summit&&<p>Reserveer ongeveer 90 minuten voor de vragen en 60 minuten voor je constructie- en papierwerk. Dit is een oefenproef gebaseerd op het lesmateriaal en het aangeleverde tentamen uit 2018.</p>}<Button disabled={!ids.length} onClick={()=>setStarted(true)}>Begin {summit?'de proef':'de levelcheck'} <ArrowRight/></Button></div>:!finished?<QuestionCard key={sessionId+ids[index]} question={QUESTIONS[ids[index]]} context="check" sessionId={sessionId} save={save} onNext={(correct,answer)=>{const event=events.filter(e=>e.type==='answer'&&e.payload.sessionId===sessionId&&e.payload.questionId===ids[index]).at(-1);setResults(r=>[...r,{id:ids[index],correct,answer,working:String(event?.payload.working||'')}])}} number={results.length+1} total={ids.length}/>:<div className="check-results"><span className="pill"><Target/>JE RESULTAAT</span><h1 className="page-title">{allCorrect?'Deze check is gehaald.':'Je weet waar je verder kunt.'}</h1><p>{results.filter(r=>r.correct).length} van {ids.length} antwoorden goed. {allCorrect?'Controleer ook je constructies en schriftelijke redeneringen.':'Bekijk per vraag welke aanpak helpt. Oefen de betrokken onderwerpen en maak daarna een nieuwe poging.'}</p><div className="check-review">{results.map((r,i)=><article key={r.id}><span className={r.correct?'correct-tag':'review-tag'}>{r.correct?<Check/>:<RotateCcw/>}Vraag {i+1}</span><h3>{QUESTIONS[r.id].prompt}</h3><p>Jouw antwoord: {QUESTIONS[r.id].type==='choice'?QUESTIONS[r.id].options?.find(o=>o.id===r.answer[0])?.text:r.answer.join(', ')}</p>{r.working&&<blockquote>{r.working}</blockquote>}<QuestionFigure question={QUESTIONS[r.id]} reveal/><CorrectAnswer question={QUESTIONS[r.id]}/><p>{QUESTIONS[r.id].explanation}</p>{QUESTIONS[r.id].working&&<p className="muted">Vergelijk de gekozen hulpfiguur, je argumenten en je rekenstappen. Een juiste uitkomst alleen bewijst nog geen juiste redenering.</p>}</article>)}</div><div className="question-actions"><Button onClick={onBack}>Bekijk mijn voortgang <ArrowRight/></Button><Button variant="outline" onClick={()=>{setSessionId(newEventId());setResults([]);setStarted(false)}}>Nieuwe poging</Button></div></div>}</section>
}
export function Practice({events,save,onBack}:{events:LearningEvent[];save:SaveEvent;onBack:()=>void}){
 const [sessionId]=useState(()=>newEventId()),[index,setIndex]=useState(0),[done,setDone]=useState(false);
 const ids=useMemo(()=>{const p=deriveProgress(events);const needed=BANK.blocks.filter(b=>b.questionIds.some(id=>p.evidence[id]&&!p.evidence[id].independent));const available=BANK.blocks.filter(b=>p.complete.includes(b.id));const priority=shuffled(needed.flatMap(b=>b.retestIds),sessionId).sort((a,b)=>Number(!!p.evidence[a]?.correct)-Number(!!p.evidence[b]?.correct));const review=shuffled(available.flatMap(b=>b.retestIds).filter(id=>!priority.includes(id)),sessionId);return [...priority.slice(0,4),...review.slice(0,2),...priority.slice(4)].slice(0,6)},[]);
 return <section><div className="section-top"><Button variant="ghost" onClick={onBack}><ArrowLeft/>Mijn route</Button><span className="eyebrow">GERICHT OEFENEN</span></div>{!ids.length?<div className="check-intro"><h1 className="page-title">Eerst een basis leggen.</h1><p>Rond een blok af. Hier verschijnen daarna vragen die aansluiten bij wat je nog lastig vindt.</p><Button onClick={onBack}>Naar mijn route</Button></div>:done?<div className="block-summary"><CheckCircle2 className="large-icon"/><h1 className="page-title">Goed dat je terugkwam.</h1><p>Je oefende de onderwerpen waarbij nog steun nodig was. De levelcheck en het papierwerk blijven apart zichtbaar.</p><Button onClick={onBack}>Bekijk mijn route</Button></div>:<><p className="muted">Deze reeks is gekozen op basis van je eerdere antwoorden en gebruikte hulp.</p><QuestionCard key={ids[index]} question={QUESTIONS[ids[index]]} sessionId={sessionId} context="retest" save={save} number={index+1} total={ids.length} onNext={()=>{if(index+1===ids.length)setDone(true);else setIndex(index+1)}} seen={!!deriveProgress(events).evidence[ids[index]]}/></>}</section>
}
