'use client';
import {newEventId} from './identity';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Box,ArrowUpRight,ArrowRight,ArrowLeft,Check,CheckCircle2,ChevronRight,Flame,LockKeyhole,Mountain,BookOpen,Timer,Target,PenLine,RefreshCw,ChartNoAxesCombined,CloudCheck,Rotate3D,Sparkles,Flag} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import Geometry from './geometry';
import {BANK,LEVELS,CHECKS,COURSE,blocksForLevel,SKILLS,SKILL_NAMES,deriveProgress,type LearningEvent,type Block} from './model';
import {LearningView,LevelCheck,Practice} from './learning';
import Workbench from './workbench';
import ConstructionLab from './construction-lab';
import CoursePaper from './course-paper';
import {CONSTRUCTION_TASKS} from './course-construction';
import Paper from './paper';
import RouteHeader from './route-header';
import {levelOneRoute} from './route-progress';
import {getBlockDiagnosis} from './diagnostic';
import {createLocalProgressStore,MAX_PROGRESS_CHARACTERS} from './local-progress';
import {APP_VERSION} from './version';

type View='lab'|'route'|'learn'|'check'|'practice'|'summary'|'workbench'|'paper'|'level';
function mergeEvents(old:LearningEvent[],next:LearningEvent[]){return [...new Map([...old,...next].map(e=>[e.id,e])).values()].sort((a,b)=>a.at-b.at||a.id.localeCompare(b.id))}
function Ring({value,number,locked=false}:{value:number;number:number;locked?:boolean}){const r=25,c=2*Math.PI*r;return <div className={'level-ring '+(number===7?'top-ring':'')}><svg viewBox="0 0 64 64" role="img" aria-label={locked?'Nog niet beschikbaar':`${Math.round(value)} procent van de levelonderdelen afgerond`}><circle cx="32" cy="32" r={r} fill="none" stroke="currentColor" opacity=".16" strokeWidth="4"/><circle cx="32" cy="32" r={r} fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={c*(1-value/100)} transform="rotate(-90 32 32)"/></svg><span>{number===7?<Mountain/>:number}</span></div>}
export default function Ruimteklaar({local=false}:{local?:boolean}){
 const localStore=useMemo(()=>createLocalProgressStore(()=>window.localStorage),[]);const [transferMessage,setTransferMessage]=useState('');
 const [events,setEvents]=useState<LearningEvent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[auth,setAuth]=useState(false),[view,setView]=useState<View>('route'),[blockId,setBlockId]=useState(BANK.blocks[0].id),[levelId,setLevelId]=useState(1);const [taskId,setTaskId]=useState(''),[paperKey,setPaperKey]=useState('1'),[checkKey,setCheckKey]=useState('1'),[attemptKey,setAttemptKey]=useState(0);const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer)},[]);const initialized=useRef(false);const pending=useRef<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);setError('');try{if(local){const d=localStore.load();setEvents(d.events);if(!d.ok)throw new Error(d.error);return}const r=await fetch('/api/progress',{cache:'no-store'});const d=await r.json() as {events:LearningEvent[];error?:string};if(!r.ok){setAuth(r.status===401);throw new Error(d.error)}setEvents(old=>mergeEvents(old,d.events));setAuth(false)}catch(e){setError(e instanceof Error?e.message:'Je voortgang is tijdelijk niet bereikbaar.')}finally{setLoading(false)}},[local,localStore]);
 useEffect(()=>{void load();if(!local)return;const refresh=()=>void load();window.addEventListener('storage',refresh);return()=>window.removeEventListener('storage',refresh)},[load,local]);
 const save=useCallback(async(type:LearningEvent['type'],payload:Record<string,unknown>)=>{const key=JSON.stringify({type,payload});const id=pending.current[key]??=newEventId();setSaving(true);setError('');try{if(local){const d=localStore.append({id,type,payload});if(!d.ok)throw new Error(d.error);setEvents(d.events);delete pending.current[key];return true}const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,type,payload})});const d=await r.json() as {events:LearningEvent[];error?:string};if(!r.ok)throw new Error(d.error);setEvents(old=>mergeEvents(old,d.events));delete pending.current[key];return true}catch(e){setError(e instanceof Error?e.message:'Je antwoord is nog niet opgeslagen.');return false}finally{setSaving(false)}},[local,localStore]);
 function exportProgress(){const d=localStore.exportProgress();if(!d.ok||!d.text){setTransferMessage(d.error||'Exporteren is niet gelukt.');return}const url=URL.createObjectURL(new Blob([d.text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Space-tent-voortgang.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setTransferMessage('Je voortgangsbestand is klaargezet. Bewaar het zelf om op een ander apparaat verder te gaan.')}
 async function importProgress(file?:File){if(!file)return;if(file.size>MAX_PROGRESS_CHARACTERS){setTransferMessage('Dit bestand is te groot.');return}try{const d=localStore.importProgress(await file.text());if(!d.ok){setTransferMessage(d.error||'Importeren is niet gelukt.');return}setEvents(d.events);setTransferMessage('Voortgang samengevoegd. Je eerdere werk is behouden.')}catch{setTransferMessage('Het bestand kon niet worden gelezen.')}}
 const p=useMemo(()=>deriveProgress(events),[events]),block=BANK.blocks.find(b=>b.id===blockId)!;
 useEffect(()=>{if(!loading&&!initialized.current){initialized.current=true;setLevelId(LEVELS.find(l=>!p.levels[l.id].passed)?.id||7)}},[loading,p]);
 const lp=p.levels[levelId],bs=blocksForLevel(levelId),unlocked=levelId===1||p.levels[levelId-1].passed;
 const tasks=CONSTRUCTION_TASKS.filter(t=>t.level===levelId),nextBlock=bs.find(b=>!p.complete.includes(b.id));
 function go(v:View){setView(v);window.scrollTo({top:0,behavior:'instant'})}
 function start(b:Block){setBlockId(b.id);setLevelId(b.level||1);go('learn')}
 function check(key=String(levelId)){setCheckKey(key);setAttemptKey(n=>n+1);go('check')}
 function paper(key=String(levelId)){setPaperKey(key);go('paper')}
 function lab(id:string){setTaskId(id);go('lab')}
 function next(){if(!unlocked){setLevelId(Math.max(1,levelId-1));go('route');return}if(nextBlock){start(nextBlock);return}const t=tasks.find(t=>!p.constructions.some(e=>e.payload.taskId===t.id&&(levelId!==7||!e.payload.helped)));if(t){lab(t.id);return}if(levelId===7){go('level');return}if(!lp.check)check();else if(!lp.paper)paper();else if(levelId<7){setLevelId(levelId+1);go('route')}else go('summary')}
 function selectLevel(id:number){setLevelId(id);go('route')}
 const activeTab=view==='summary'?'summary':view==='practice'?'practice':'route';
 function SkillBars(){return <div className="skill-bars">{SKILLS.map(s=>{const x=lp.skills[s];return <div key={s}><div className="skill-heading"><span>{SKILL_NAMES[s]}</span><span>{x.independent}/{x.total}</span></div><div className="evidence-bar" role="img" aria-label={`${x.independent} van ${x.total} direct zelfstandig goed; ${x.helped} na hulp of herhaling`}><span className="independent" style={{width:`${x.total?x.independent/x.total*100:0}%`}}/><span className="assisted" style={{width:`${x.total?x.helped/x.total*100:0}%`}}/></div></div>})}<div className="bar-legend"><span><i className="independent"/>Zelfstandig</span><span><i className="assisted"/>Na hulp / herhaling</span></div></div>}
 function BlockRows(){return <div className="block-list">{bs.map((b,i)=>{const done=p.complete.includes(b.id),open=unlocked&&(i===0||p.complete.includes(bs[i-1].id)),answered=b.questionIds.filter(id=>p.evidence[id]).length;return <button type="button" key={b.id} className="block-row" disabled={!open||loading} onClick={()=>start(b)}><span className={'block-icon '+(done?'done':'')}>{done?<Check/>:open?<BookOpen/>:<LockKeyhole/>}</span><span className="block-text"><strong>{b.title}</strong><small>{done?'Blok afgerond':`${answered}/${b.questionIds.length} oefenvragen · uitleg en nieuwe toepassing`}</small></span><span className="duration"><Timer/>20 min</span><ChevronRight/></button>})}</div>}
 function Milestones(){return <div className="finishing-tasks">{tasks.map(t=>{const done=p.constructions.some(e=>e.payload.taskId===t.id&&(levelId!==7||!e.payload.helped));return <button key={t.id} disabled={!unlocked||loading} onClick={()=>lab(t.id)}><span>{done?<CheckCircle2/>:<PenLine/>}<strong>{t.title}</strong></span><span>{done?'Afgerond':'Construeren'}<ChevronRight/></span></button>})}{levelId!==7&&<><button disabled={!unlocked||lp.blocks<bs.length} onClick={()=>check()}><span>{lp.check?<CheckCircle2/>:<Target/>}<strong>Zelfstandige levelcheck</strong></span><span>{lp.check?'Gehaald':`${CHECKS[levelId]?.length||0} gemengde vragen`}<ChevronRight/></span></button><button disabled={!unlocked} onClick={()=>paper()}><span>{lp.paper?<CheckCircle2/>:<PenLine/>}<strong>Op papier toepassen</strong></span><span>{lp.paper?'Zelfgecontroleerd':'Potlood & geodriehoek'}<ChevronRight/></span></button></>}</div>}
 function Summit(){const bReady=!!p.retentionReadyAt&&now>=p.retentionReadyAt;return <div className="top-contract"><h2>Alle stof, zelfstandig toegepast.</h2><p>Twee verschillende gemengde proeven verbinden de zes leslevels. Je kiest de methode, rekent, construeert en onderbouwt zonder hints. De digitale uitkomsten en constructies worden gecontroleerd; je schriftelijke redeneringen beoordeel je met de uitwerking.</p><div className="summit-criteria">{[['a','Proef A','Begin nadat alle zes leslevels zijn behaald.'],['b','Proef B · later opnieuw','Een andere proef, minstens 24 uur na een geslaagde proef A.']].map(([key,title,text])=><article key={key}><span>{p.checks['7'+key]?<CheckCircle2/>:<Target/>}</span><div><h3>{title}</h3><p>{text}</p>{key==='b'&&p.retentionReadyAt&&!bReady&&<p>Beschikbaar vanaf {new Date(p.retentionReadyAt).toLocaleString('nl-NL')}.</p>}<div className="question-actions"><Button disabled={!unlocked||(key==='b'&&!bReady)} onClick={()=>check('7'+key)}>{p.checks['7'+key]?'Proef opnieuw maken':'Start '+title}<ArrowRight/></Button><Button variant="outline" disabled={!unlocked} onClick={()=>paper('7'+key)}>Papierwerk {key.toUpperCase()}</Button></div></div></article>)}</div><Milestones/><p className="muted">Topstatus betekent dat je aan de criteria van deze voorbereidingsroute hebt voldaan, inclusief jouw zelfcontrole op papier. Controleer bij je opleiding de actuele tentamenstof en laat twijfel over bewijs of tekenwerk nakijken. Het is geen garantie voor een tentamencijfer.</p>{lp.passed&&<div className="success-panel"><Mountain/><div><h2>Topniveau behaald.</h2><p>Je hebt alle leslevels, beide proeven, zelfstandige digitale constructies en je papieren zelfcontroles afgerond.</p></div></div>}</div>}
 return <main className="app-shell">{local&&<nav className="space-exit no-print" aria-label="Wisik"><a href="/rafelrand/">← Rafelrandjes</a><span>Space-tent</span><a href="/">Wisik-terrein ↗</a></nav>}<header className="masthead no-print"><button className="brand" onClick={()=>go('route')} aria-label="Ruimteklaar, naar mijn route"><Box/><span>ruimte<span className="orange">klaar</span><small className="brand-edition">editie {APP_VERSION}</small></span></button><div className="header-progress"><span className="xp"><Flame/>{p.xp}<small>XP</small></span><span className="level-total"><Flag/>{Object.values(p.levels).filter(l=>l.passed).length} / 7 levels</span></div></header><RouteHeader progress={p} level={view==='workbench'?2:levelId} currentBlockId={view==='learn'?blockId:undefined} working={['learn','check','practice','paper','workbench','lab'].includes(view)} loading={loading} onContinue={next}/><div className="subnav no-print"><Tabs value={activeTab} onValueChange={v=>go(v as View)}><TabsList variant="line"><TabsTrigger value="route">Mijn route</TabsTrigger><TabsTrigger value="practice">Gericht oefenen</TabsTrigger><TabsTrigger value="summary">Mijn inzicht</TabsTrigger></TabsList></Tabs><span className="save-state">{loading?'Voortgang ophalen…':saving?'Bewaren…':error?'Nog niet opgeslagen':<><CloudCheck/>{local?'Bewaard op dit apparaat':'Voortgang bewaard'}</>}</span></div>{error&&<div className="error-banner no-print" role="alert"><span>{error}</span>{auth?<a className="signin-link" href="/signin-with-chatgpt?return_to=%2F" target="_top">Aanmelden</a>:<Button variant="outline" onClick={load}>Opnieuw laden</Button>}</div>}
 {local&&view==='route'&&<details className="local-progress no-print"><summary>Je voortgang meenemen</summary><p>Je antwoorden, berekeningen en voortgang blijven in deze browser. Er is geen account en er worden geen leerresultaten naar Wisik verstuurd. Met een bestand kun je zelf op een ander apparaat verder. Wissen van browsergegevens verwijdert je voortgang.</p><div className="view-buttons"><Button variant="outline" onClick={exportProgress}>Voortgang downloaden</Button><label className="import-progress">Voortgang importeren<input type="file" accept=".json,application/json" onChange={e=>{void importProgress(e.target.files?.[0]);e.target.value=''}}/></label></div><p role="status">{transferMessage}</p></details>}
 {(view==='route'||view==='level')&&<><section className="journey compact-journey"><div className="section-heading"><h2>Jouw route naar het topniveau.</h2><span className="edition-badge">Zes lessen + het toplevel</span></div><div className="level-track">{LEVELS.map(l=><button key={l.id} className={'level-tile '+(l.id===levelId?'current':'')+(l.id===7?' summit':'')} onClick={()=>selectLevel(l.id)} aria-current={l.id===levelId?'step':undefined}><Ring value={p.levels[l.id].percent} number={l.id}/><span className="level-caption">{l.id===7?'TOPLEVEL':`LEVEL 0${l.id}`}</span><strong>{l.title}</strong><span>{p.levels[l.id].passed?'Behaald':l.id>1&&!p.levels[l.id-1].passed?'Na level '+(l.id-1):'Aan de slag'}</span></button>)}</div></section><section className="course-intro"><div><span className="pill">LEVEL {String(levelId).padStart(2,'0')} · {levelId===7?'ALLES SAMEN':`LES 1.${levelId}`}</span><h1 className="page-title">{LEVELS[levelId-1].title}</h1><p className="intro">{LEVELS[levelId-1].subtitle}</p></div><div className="course-intro-action"><Button onClick={next} disabled={loading}>{!unlocked?'Eerst level '+(levelId-1)+' afronden':lp.passed?'Volgende uitdaging':'Verder oefenen'}<ArrowRight/></Button><span className="muted">Eén blok: ongeveer 20 minuten</span></div></section>{!unlocked&&<p className="availability"><LockKeyhole/>Rond level {levelId-1} af om deze leerroute te openen. Hieronder zie je welke onderwerpen en constructies je daarna leert.</p>}{levelId===7?<Summit/>:<div className="overview-grid"><div><BlockRows/><Milestones/></div><aside className="progress-panel"><h2>Zo groeit je inzicht.</h2><SkillBars/><p className="muted">Groen: meteen zelfstandig goed. Oranje: goed na hulp of herhaling. De levelcheck en je constructies toetsen de toepassing.</p><Button variant="outline" onClick={()=>go('summary')}>Bekijk je terugkoppeling <ArrowRight/></Button></aside></div>}{levelId===1&&<section className="atelier-invite"><div><h2>Alvast een constructie onderzoeken?</h2><p>Probeer het oefenatelier met een kubus, ook op je telefoon.</p></div><Button variant="outline" onClick={()=>go('workbench')}>Open het oefenatelier <ArrowUpRight/></Button></section>}</>}
 {view==='learn'&&<LearningView key={blockId} block={block} events={events} save={save} onBack={()=>go('route')} onDone={()=>{const i=bs.findIndex(b=>b.id===blockId);if(i+1<bs.length)start(bs[i+1]);else go('summary')}}/>}
 {view==='check'&&<LevelCheck key={checkKey+'-'+attemptKey} checkKey={checkKey} events={events} save={save} onBack={()=>go('route')}/>}
 {view==='practice'&&<Practice key={attemptKey} events={events} save={save} onBack={()=>go('route')}/>}
 {view==='workbench'&&<Workbench save={save} onBack={()=>go('route')}/>}
 {view==='lab'&&CONSTRUCTION_TASKS.find(t=>t.id===taskId)&&<ConstructionLab key={taskId} task={CONSTRUCTION_TASKS.find(t=>t.id===taskId)!} events={events} save={save} onBack={()=>go('route')}/>}
 {view==='paper'&&(paperKey==='1'?<Paper save={save} onBack={()=>go('route')} alreadyDone={p.paperDone}/>:<CoursePaper key={paperKey} paperKey={paperKey} save={save} onBack={()=>go('route')} alreadyDone={events.some(e=>e.type==='paper'&&e.payload.level===paperKey&&Array.isArray(e.payload.checks)&&e.payload.checks.length===4)}/>)}
 {view==='summary'&&<section className="insight-view"><span className="eyebrow">JOUW LEERBEELD · LEVEL {String(levelId).padStart(2,'0')}</span><h1 className="page-title">Wat je al kunt.<br/><span className="orange">En wat je verder brengt.</span></h1><div className="overview-grid"><div><div className="milestone-banner">{lp.passed?<CheckCircle2/>:<Target/>}<div><h2>{lp.passed?`Level ${levelId} behaald.`:`Op weg naar level ${levelId}.`}</h2><p>{lp.blocks} van {bs.length} blokken afgerond. Levelcheck: {lp.check?'gehaald':'nog te doen'}. Constructies: {lp.construction?'afgerond':'nog te doen'}. Papier: {lp.paper?'zelfgecontroleerd':'nog te doen'}.</p></div></div>{bs.map(b=>{const independent=b.questionIds.filter(id=>p.evidence[id]?.independent).length,helped=b.questionIds.filter(id=>p.evidence[id]?.correct&&!p.evidence[id]?.independent).length,needs=b.questionIds.filter(id=>p.evidence[id]&&!p.evidence[id].correct).length,diagnosis=getBlockDiagnosis(b,events);return <article className="insight-row" key={b.id}><h3>{b.title}</h3><p>{independent} van {b.questionIds.length} direct zelfstandig goed. {helped} goed na hulp of herhaling. {needs>0?`${needs} vraagt nog oefening.`:!b.questionIds.some(id=>p.evidence[id])?'Nog niet onderzocht.':''}</p>{diagnosis&&<p className="diagnosis-row">{diagnosis.investigated?diagnosis.supported?'De controlevragen ondersteunen het vermoeden: ':'Het vermoeden is niet eenduidig bevestigd: ':'Een fout gaf aanleiding tot gerichte controlevragen: '}{b.misconception.label}. {diagnosis.retested?'De herstelvragen gingen goed; herhaling volgt in gericht oefenen.':''}</p>}<Button variant="ghost" disabled={!unlocked} onClick={()=>start(b)}>Blok herhalen <ArrowRight/></Button></article>})}{tasks.map(t=>{const e=p.constructions.filter(e=>e.payload.taskId===t.id).at(-1);return <article className="insight-row" key={t.id}><h3>{t.title}</h3><p>{e?(e.payload.helped?'Afgerond met hulp of na feedback.':'Deze constructie werd zonder aanwijzingen afgerond.'):'Nog niet afgerond.'}</p></article>})}</div><aside className="progress-panel"><h2>Vier kanten van beheersing.</h2><SkillBars/><Button className="wide-button" onClick={()=>go('practice')}>Gericht verder oefenen <ArrowRight/></Button><Button variant="outline" className="wide-button" onClick={next}>Volgende stap in je route</Button></aside></div>{levelId===7&&<Summit/>}</section>}
 <footer className="site-footer no-print">{local&&<a href="/rafelrand/space-tent/">Over Space-tent en de controles ↗</a>}<span>Een initiatief van Edwin van der Plas</span><span>Bij HAN Ruimtemeetkunde 2025–2026 · editie {APP_VERSION}</span></footer></main>
}
